### PR TITLE
fix crash caused by empty delegates when use clusterNetwork

### PR DESCRIPTION
**Pull request by hanxueluo**
Signed-off-by: Huanle Han <hanhuanle@caicloud.io>

### CODE REVIEW

**Comment by dougbtv** [comment]
Thanks for the contribution! Can you provide some unit test cases for this one? Appreciate it

**Comment by hanxueluo** [comment]
I have added a test case. Without the fix, the test case would run to failure:
```
•! Panic [5.483 seconds]
multus operations
/root/go/src/github.com/intel/multus-cni/multus/multus_test.go:148
  executes clusterNetwork delegate [It]
  /root/go/src/github.com/intel/multus-cni/multus/multus_test.go:507

  Test Panicked
  runtime error: index out of range
  /usr/lib/go/src/runtime/panic.go:502

  Full Stack Trace
  	/usr/lib/go/src/runtime/panic.go:502 +0x229
  github.com/intel/multus-cni/k8sclient.TryLoadPodDelegates(0xc42031c4b0, 0xc4201b03c0, 0x1210de0, 0xc420167160, 0x0, 0x0, 0x1aea8f0, 0xc4203aa84b)
  	/root/go/src/github.com/intel/multus-cni/k8sclient/k8sclient.go:438 +0x629
  github.com/intel/multus-cni/multus.cmdDel(0xc420136000, 0x1210da0, 0xc4201aab10, 0x1210de0, 0xc420167160, 0x0, 0x0)
  	/root/go/src/github.com/intel/multus-cni/multus/multus.go:416 +0x37c
  github.com/intel/multus-cni/multus.glob..func1.8()
  	/root/go/src/github.com/intel/multus-cni/multus/multus_test.go:554 +0xafa
  github.com/intel/multus-cni/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4200cdc80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/root/go/src/github.com/intel/multus-cni/multus/multus_test.go:43 +0x64
  testing.tRunner(0xc42039e0f0, 0x1199680)
  	/usr/lib/go/src/testing/testing.go:777 +0xd0
  created by testing.(*T).Run
  	/usr/lib/go/src/testing/testing.go:824 +0x2e0
```

**Comment by hanxueluo** [comment]
@dougbtv @rkamudhan 
Could you take a look? Thanks

**Comment by dougbtv** [comment]
I think this is ready to roll, thank you @hanxueluo for the contribution!!!

**Pull request merged**
