### PR TITLE
[WIP] Support gateway in NetworkSelectionElement

### PR DESCRIPTION
**Pull request by dougbtv**
Additionally, changes config JSON from to use the `default-route` terminology, and adds to docs

### CODE REVIEW

**Comment by s1061123** [comment]
Thank you for your PR!

Could you please add test case for it?

**Comment by s1061123** [comment]
Another question. Once we change default gw to non kubernetes network, then how k8s VIP (e.g. IP for service) works?

**Comment by dougbtv** [comment]
@s1061123 Tomo, something I ran into is that for making an option for using the default cluster cidr as a static route is that...

#1: You can't directly query the API for the cluster-cidr, see: https://github.com/kubernetes/kubernetes/issues/46508

#2: Additionally, at least Flannel adds a route to the cluster-cidr, which is in addition to the default route, so, for example, you wind up with pods that can route services to/from the default network:

```
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it samplepod -- ip route
default via 192.168.2.2 dev net1 
10.244.0.0/24 dev eth0  proto kernel  scope link  src 10.244.0.102 
10.244.0.0/16 via 10.244.0.1 dev eth0 
192.168.2.0/24 dev net1  proto kernel  scope link  src 192.168.2.202 
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1120: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether 52:4b:05:86:a1:99 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.102/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 06:e9:26:72:ea:8c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.2.202/24 scope global net1
       valid_lft forever preferred_lft forever
```

I got half way there towards making this feature, but, not going to push it up for now, I'll talk to you first before I move further forward.

I'll put up the rest of the updates though here shortly, which address:

* Making sure the specified route in the `default-route` annotation is used, and
* Makes sure the network status results are aligned with the spec.

**Comment by dougbtv** [comment]
New commit pushed up and rebased... Still todo: test cases (and discuss cluster cidr)

Test scenario for annotated pod:

```
[centos@kube-singlehost-master multus-cni]$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "macvlan-conf",
      "default-route": ["192.168.2.2"]
    }]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
EOF
pod/samplepod created
[centos@kube-singlehost-master multus-cni]$ watch -n1 kubectl get pods --all-namespaces
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1121: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether f2:b6:a5:cf:3b:d2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.103/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether ba:3f:6c:6d:6f:b9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.2.203/24 scope global net1
       valid_lft forever preferred_lft forever
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it samplepod -- ip route
default via 192.168.2.2 dev net1 
10.244.0.0/24 dev eth0  proto kernel  scope link  src 10.244.0.103 
10.244.0.0/16 via 10.244.0.1 dev eth0 
192.168.2.0/24 dev net1  proto kernel  scope link  src 192.168.2.203 
[centos@kube-singlehost-master multus-cni]$ kubectl describe pod samplepod 
Name:         samplepod
Namespace:    default
Priority:     0
Node:         kube-singlehost-master/192.168.122.41
Start Time:   Fri, 25 Oct 2019 19:13:24 +0000
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: [{ "name": "macvlan-conf", "default-route": ["192.168.2.2"] }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "cbr0",
                    "interface": "eth0",
                    "ips": [
                        "10.244.0.103"
                    ],
                    "mac": "f2:b6:a5:cf:3b:d2",
                    "dns": {}
                },{
                    "name": "macvlan-conf",
                    "interface": "net1",
                    "ips": [
                        "192.168.2.203"
                    ],
                    "mac": "ba:3f:6c:6d:6f:b9",
                    "dns": {},
                    "default-route": [
                        "192.168.2.2"
                    ]
                }]
Status:       Running
IP:           10.244.0.103
IPs:
  IP:  10.244.0.103
Containers:
  samplepod:
    Container ID:  docker://95dd2cfb105ff49f47807ff7f190a35e8e91df8bd01e34f159279ac1575ce08d
    Image:         dougbtv/centos-network
    Image ID:      docker-pullable://dougbtv/centos-network@sha256:74cb74f6fe64f49037d3460f60003ea6e7455ce0c7646b2badcf5a8f0811f397
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      trap : TERM INT; sleep infinity & wait
    State:          Running
      Started:      Fri, 25 Oct 2019 19:13:32 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4wj9d (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-4wj9d:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4wj9d
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                             Message
  ----    ------     ----       ----                             -------
  Normal  Scheduled  <unknown>  default-scheduler                Successfully assigned default/samplepod to kube-singlehost-master
  Normal  Pulling    13s        kubelet, kube-singlehost-master  Pulling image "dougbtv/centos-network"
  Normal  Pulled     13s        kubelet, kube-singlehost-master  Successfully pulled image "dougbtv/centos-network"
  Normal  Created    12s        kubelet, kube-singlehost-master  Created container samplepod
  Normal  Started    12s        kubelet, kube-singlehost-master  Started container samplepod
```

test scenario for pod without annotation:

```
[centos@kube-singlehost-master multus-cni]$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: vanilla
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "macvlan-conf" 
    }]'                               
spec:
  containers:
  - name: vanilla
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
EOF                              

pod/vanilla created
[centos@kube-singlehost-master multus-cni]$ watch -n1 kubectl get pods --all-namespaces
[centos@kube-singlehost-master multus-cni]$ kubectl describe pod vanilla
Name:         vanilla
Namespace:    default
Priority:     0
Node:         kube-singlehost-master/192.168.122.41
Start Time:   Fri, 25 Oct 2019 19:15:15 +0000
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: [{ "name": "macvlan-conf" }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "cbr0",
                    "interface": "eth0",
                    "ips": [
                        "10.244.0.104"
                    ],
                    "mac": "46:99:20:11:45:e4",
                    "dns": {},
                    "default-route": [
                        "10.244.0.1"
                    ]
                },{
                    "name": "macvlan-conf",
                    "interface": "net1",
                    "ips": [
                        "192.168.2.204"
                    ],
                    "mac": "ae:31:cd:fc:6b:f1",
                    "dns": {}
                }]
Status:       Running
IP:           10.244.0.104
IPs:
  IP:  10.244.0.104
Containers:
  vanilla:
    Container ID:  docker://45f422a24f2517ffff019d9d69260710d0424f3bfd11fce4e94e83facaee96a7
    Image:         dougbtv/centos-network
    Image ID:      docker-pullable://dougbtv/centos-network@sha256:74cb74f6fe64f49037d3460f60003ea6e7455ce0c7646b2badcf5a8f0811f397
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      trap : TERM INT; sleep infinity & wait
    State:          Running
      Started:      Fri, 25 Oct 2019 19:15:22 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4wj9d (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-4wj9d:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4wj9d
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                             Message
  ----    ------     ----       ----                             -------
  Normal  Scheduled  <unknown>  default-scheduler                Successfully assigned default/vanilla to kube-singlehost-master
  Normal  Pulling    7s         kubelet, kube-singlehost-master  Pulling image "dougbtv/centos-network"
  Normal  Pulled     6s         kubelet, kube-singlehost-master  Successfully pulled image "dougbtv/centos-network"
  Normal  Created    6s         kubelet, kube-singlehost-master  Created container vanilla
  Normal  Started    6s         kubelet, kube-singlehost-master  Started container vanilla
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it vanilla -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1122: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether 46:99:20:11:45:e4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.104/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether ae:31:cd:fc:6b:f1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.2.204/24 scope global net1
       valid_lft forever preferred_lft forever
[centos@kube-singlehost-master multus-cni]$ kubectl exec -it vanilla -- ip route
default via 10.244.0.1 dev eth0 
10.244.0.0/24 dev eth0  proto kernel  scope link  src 10.244.0.104 
10.244.0.0/16 via 10.244.0.1 dev eth0 
192.168.2.0/24 dev net1  proto kernel  scope link  src 192.168.2.204 
```

**Comment by s1061123** [comment]
In case of flannel, it automatically adds the cluster cidr/service-cluster-ip, however it is not universal among Kubernetes CNI plugins. 
I tested it with weave and weave does not add the routes, hence we need to add some option (conifg) to add the route.

I also agree that we merge this PR first and let's take care of it in another PR.

```
[root@kube-master ~]# grep cluster /etc/kubernetes/manifests/kube-controller-manager.yaml
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --service-cluster-ip-range=10.96.0.0/12
[centos@kube-master ~]$ cat /etc/cni/net.d/10-weave.conflist 
{
    "cniVersion": "0.3.0",
    "name": "weave",
    "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
[centos@kube-master ~]$ kubectl exec -it centos ip route
default via 10.40.0.0 dev eth0 
10.32.0.0/12 dev eth0 proto kernel scope link src 10.40.0.2 
```

**Pull request merged**
