### PR TITLE
Demo examples including updates

### PR DESCRIPTION
**Pull request by dougbtv**
@s1061123 I went ahead and added your demo files into a `./examples/demo` directory -- but, I also went ahead and updated them so that they match the spec section that looks like:

```
metadata:
  name: flannel-conf
spec: 
  config: '{
            "cniVersion": "0.3.0",
```

E.g. now the `plugin:` top level element is gone, and the `"type": ` element is under `spec.config`. 

Tomo, feel free to commit to this branch to show the changes, or, we can later delete this branch if you want to do it another way.

*note* Don't merge this yet, just for discussion of the demo examples for now, can merge later if we keep this branch, or close out the PR if we don't need it.

### CODE REVIEW

**Comment by s1061123** [comment]
Feng mentioned that we should rename 'demo' to 'demo1' or some for another demo and I agree with him.
I will rename it.

**Comment by dougbtv** [comment]
Sounds like a good idea

**Comment by s1061123** [comment]
Now it is ready, so removing 'WIP' tag.

Could you please take a look into it?

**Comment by rkamudhan** [comment]
@s1061123 @dougbtv I will look into it..

**Comment by s1061123** [comment]
I've rebased and make it as one commit.

**Pull request merged**
