### PR TITLE
Push new images on every merge to master.

### PR DESCRIPTION
**Pull request by SchSeba**
It will be nice to get a new latest image on every merge to master.

### CODE REVIEW

**Comment by dougbtv** [comment]
Hey @SchSeba -- I have a pull request I'm brewing for this one. It's available in this branch, it should go in soon. https://github.com/intel/multus-cni/tree/travis-ci

The gist is that we'd like the `:latest` to be the latest tagged version. And we'll have `:snapshot` be the latest tip of master.

**Comment by SchSeba** [comment]
@dougbtv Sounds good to me thanks!

**Comment by dougbtv** [comment]
Also just FYI that there's a `:snapshot` available now that is latest tip, built late last week!

Thanks regardless for the PR, for sure!

**Comment by SchSeba** [comment]
@dougbtv I need this commit https://github.com/intel/multus-cni/commit/ec543570b5604c783e70410cc98405fa8a944915 and is not on the last snapshot build

**Comment by dougbtv** [comment]
Hrmmm, kind of looks like it's there... 

```
[root@imagebuilder multus-cni]# docker run -it --entrypoint=/bin/bash nfvpe/multus:snapshot
[root@e0e41fc4ec50 /]# cat /usr/src/multus-cni/multus/multus.go | grep IgnoreUnknown
		if os.Setenv("CNI_ARGS",fmt.Sprintf("%s;IgnoreUnknown=true;MAC=%s", os.Getenv("CNI_ARGS"), delegate.MacRequest)) != nil {
[root@e0e41fc4ec50 /]# exit
exit
[root@imagebuilder multus-cni]# docker images | grep snapshot
docker.io/nfvpe/multus      snapshot            6561da039be5        3 days ago          412 MB
nfvpe/multus                snapshot            6561da039be5        3 days ago          412 MB
```

**Comment by SchSeba** [comment]
@dougbtv  
Sorry I don't checked inside the container I checked on the travis branch and the change is not there https://github.com/intel/multus-cni/blob/travis-ci/multus/multus.go#L181.

But if the snapshot image contains it is good!
Thanks for your help!

**Comment by dougbtv** [comment]
Hey no prob for sure! Snapshot image is good to go, even just got a fresh rebuild -- I have the travis script in so you'll get new `:snapshot` images with each merge to master now, pulled in from the `travis-ci` branch in PR #194

**Pull request closed without merging**
