### PR TITLE
Add ARM64 support

### LINKED ISSUE #554: Add ARM64 Support
**What would you like to be added**:

Support for ARM64 architecture.

**Why is this needed**:

To enable the deployment of `multus` on ARM based Kubernetes clusters.

### PR DESCRIPTION
**Pull request by shaneutt**
Adds ARM64 support for Multus re-using the existing
strategy used to add ppc64le support in previous iterations.

Fixes #554

### CODE REVIEW

**Comment by shaneutt** [comment]
# Testing Notes

I scraped the scripts out of `.travis.yml` in order to test this locally.

I was able to successfully build and deploy my [own multi-arch manifest image](https://hub.docker.com/r/shaneutt/multus/tags) using the `.travis.yml` scripts and the new ARM64 Dockerfile.

I tested this on a local aarch64 based [k3s](https://k3s.io/) cluster:

```shell
$ perl -pe 's{docker.io/nfvpe/multus}{docker.io/shaneutt/multus}g' images/multus-daemonset.yml | k apply -f -
customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
clusterrole.rbac.authorization.k8s.io/multus created
clusterrolebinding.rbac.authorization.k8s.io/multus created
serviceaccount/multus created
configmap/multus-cni-config created
daemonset.apps/kube-multus-ds-amd64 created
daemonset.apps/kube-multus-ds-ppc64le created
daemonset.apps/kube-multus-ds-arm64 created
$ kubectl -n kube-system get pods -w
NAME                                     READY   STATUS              RESTARTS   AGE
local-path-provisioner-6d59f47c7-nbkvs   1/1     Running             0          64m
coredns-7944c66d8d-p29gj                 1/1     Running             0          64m
kube-multus-ds-arm64-w8ftc               0/1     ContainerCreating   0          18s
kube-multus-ds-arm64-w8ftc               1/1     Running             0          54s
$ ssh root@k8s '/opt/cni/bin/multus -v'
multus-cni version:v3.6, commit:1bb87b0ae9b2bfe3f9526e17d4d9ce4a029bfbb8, date:2020-09-11T12:58:23+0000
```

As seen in the above if anyone else is interested in testing this out you can do so running the following from my fork/branch:

```shell
perl -pe 's{docker.io/nfvpe/multus}{docker.io/shaneutt/multus}g' images/multus-daemonset.yml | k apply -f -
```

Given the results I'm ready to take this out of draft and consider it ready for review.

**Comment by s1061123** [comment]
Thank you so much for your PR, @shaneutt !

Now multus-cni no longer used travis and multus-cni uses github actions for CI.

Could you please add arm64 files as others do and modify docker*.yml ?
https://github.com/intel/multus-cni/tree/master/.github/workflows

**Comment by shaneutt** [comment]
> Thank you so much for your PR, @shaneutt !
> 
> Now multus-cni no longer used travis and multus-cni uses github actions for CI.
> 
> Could you please add arm64 files as others do and modify docker*.yml ?
> https://github.com/intel/multus-cni/tree/master/.github/workflows

Sure thing :+1:

**Comment by s1061123** [comment]
Looks good to me, thanks @shaneutt !

**Pull request merged**
