### PR TITLE
Support multi arch image and CI job

### LINKED ISSUE #305: Multi architecture image and CI job
**Add Support for creating a multi-arch docker image for both amd64 and ppc64le**

### PR DESCRIPTION
**Pull request by Mmduh-483**
Adding image amd CI job for multi archs, currently amd64 and ppc64le
fixes #305
Signed-off-by: mamduhala <mamduhala@mellanox.com>

### CODE REVIEW

**Comment by dougbtv** [comment]
@Mmduh-483 -- thanks a bunch for the PR! I really like the idea of building this on multiple architectures. 

Can you check out what's up with the Travis build? Looks like one arch is failing. Additionally -- any input on changing the daemonset YAML to deal with multiple arches, too? 

Thanks!

**Comment by dougbtv** [comment]
@Mmduh-483 -- just spoke with an associate of mine, and we have some concerns about how this might impact the current build. Would you mind joining the Multus maintainers meeting to discuss building for multiple arches? 

I went ahead and put an item on the agenda for it -- the agenda (and meeting connection info) is available here: https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit#heading=h.u8si5xqsz34u

**Comment by Mmduh-483** [comment]
@dougbtv Sorry being late, I will join the meeting next week
Regarding the Damonset file, there is no need to update it, `docker manifest` is creating like a map for each arch of amd64 & ppc64le and one the user is using a machine with amd64 arch then docker will pull the image with amd64 arch, same thing for ppc64le

**Comment by s1061123** [comment]
#352 takes care of it hence it is closed.

**Pull request closed without merging**
