### PR TITLE
Dockerfile improvements

### PR DESCRIPTION
**Pull request by micw**
Follow-up to #222

### CODE REVIEW

**Comment by dougbtv** [comment]
Thanks @micw -- still a fan of where you're going with this. I'd also like to verify that the entrypoint still works with the `/dockerfile.openshift` build too, that might also require tweaks.

**Comment by micw** [comment]
@dougbtv @intlabs finally got some time to finish it (and rebase to current master).
A docker image built with this change can soon be found at https://hub.docker.com/r/micwy/multus-cni

**Comment by micw** [comment]
@dougbtv Oh, seen that you already commented. Can you use 2-stage builds on openshift?

**Comment by micw** [comment]
@dougbtv could you please check if the modified openshift Dockerfile works for you?

**Comment by micw** [comment]
@dougbtv Can we make any progress with this? Meanwhile people are comitting to the old entrypoint, so I need to modify this PR regulary...

**Comment by micw** [comment]
Hi. I have seen that multus-cni is still being shipped with that large centos based image. Are you still interested in this PR? If so, I'd rebase it to the current master.

**Pull request closed without merging**
